# Generated by Django 3.1.4 on 2020-12-15 18:09

from django.db import migrations, models


class migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Person", 
            fields=[
                ('id', moldels.AutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),           
            ],
        ),
    ]